M48
; DRILL file {KiCad 7.0.8} date 2023 October 19, Thursday 15:00:35
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-19T15:00:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1457
%
G90
G05
T1
X4.9948Y-3.4661
X4.9948Y-3.7339
T2
X3.2Y-2.2
X3.2Y-4.8
X7.8Y-2.2
X7.8Y-4.8
T0
M30
